create table if not exists public.clientes (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  visits integer default 0,
  last_visit text,
  notes text
);

create table if not exists public.empleados (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  phone text,
  schedule text,
  status text,
  work_start time,
  work_end time
);

create table if not exists public.servicios (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  duration text,
  price numeric(10,2),
  description text,
  duration_minutes integer
);

create table if not exists public.reservas (
  id bigint generated by default as identity primary key,
  client_id bigint,
  employee_id bigint,
  service_id bigint,
  date text not null,
  time text not null,
  end_time time,
  status text default 'Pendiente'
);

alter table public.reservas
  add constraint reservas_client_id_fkey
  foreign key (client_id) references public.clientes(id)
  on delete set null;

alter table public.reservas
  add constraint reservas_employee_id_fkey
  foreign key (employee_id) references public.empleados(id)
  on delete set null;

alter table public.reservas
  add constraint reservas_service_id_fkey
  foreign key (service_id) references public.servicios(id)
  on delete set null;